name: miners-online-core

services:
  web-proxy:
    build: ./config/web-proxy
    restart: unless-stopped
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./run/web-proxy/data:/data
      - ./run/web-proxy/config:/config
      - ./config/web-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - web

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    networks:
      - web

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
    volumes:
      - ./run/mariadb/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - game-core

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      - mariadb
    networks:
      - game-core
      - web

  server-announce:
    image: ghcr.io/samuelh2005/serverannounce-backend:8ffb851cfeb88e275413eecdcb02f1b473827016
    restart: unless-stopped
    environment:
      CONFIG_PATH: /config.yaml
    volumes:
      - ./config/server-announce/config.yaml:/config.yaml:ro
    networks:
      - web

networks:
  game-core:
    external: true
  web:
    external: true
  # No minecraft network needed here
