name: miners-online-core

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
    volumes:
      - ./run/mariadb/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - game-core

  server-announce:
    image: ghcr.io/samuelh2005/serverannounce-backend:05866043ef7fd39c9817d3d04a3526a7f4d86177
    restart: unless-stopped
    environment:
      CONFIG_PATH: /config.yaml
    volumes:
      - ./config/server-announce/config.yaml:/config.yaml:ro
    networks:
      - web

networks:
  game-core:
    external: true
  web:
    external: true
  # No minecraft network needed here
