name: miners-online-core

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
    volumes:
      - ./run/mariadb/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - game-core

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - tunnel_net
      - game-core

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - game-core
    ports:
      - "6379:6379"

networks:
  tunnel_net:
    external: true
  game-core:
    external: true
  # No minecraft network needed here
