services:
  minecraft-proxy:
    image: itzg/mc-proxy:latest
    restart: unless-stopped
    environment:
      TYPE: "VELOCITY"
      ICON: "https://github.com/miners-online/.github/blob/main/profile/logos/favicon-64x64.png?raw=true"
      PLUGINS_FILE: "/config/plugins.txt"

      CFG_PROXY_SECRET: ${VELOCITY_FORWARDING_SECRET}
      CFG_DB_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
    volumes:
      - ./config/minecraft-proxy:/config
    ports:
      - '25565:25565' # Java Edition
      - '25565:25565/udp' # Java Edition query
      - '19132:19132/tcp' # Geyser listener
      - '19132:19132/udp' # Geyser listener
    networks:
      - game-core
      - minecraft

networks:
  game-core:
    external: true
  minecraft:
    external: true
  # No traefik network needed here, this is a game server, not a web service.
