name: miners-online-web

services:
  web-proxy:
    build: ./web/web-proxy
    restart: unless-stopped
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      CLOUDFLARE_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./run/web-proxy/data:/data
      - ./run/web-proxy/config:/config
      - ./web/web-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - web

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - game-core
      - web

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_DB_URL: jdbc:mysql://mariadb:3306/keycloak
      KC_DB: mysql
      KC_DB_USERNAME:  ${KEYCLOAK_ADMIN}
      KC_DB_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - game-core
      - web
    command:
      - start --http-enabled=true

networks:
  game-core:
    external: true
  web:
    external: true
  # No minecraft network needed here
