server:
  port: 3000
  default_server_expiry: 300

servers:
  # - name: lobby1
  #   address: 10.0.0.20:25565
  #   group: lobby

  - name: city-world
    address: desktop-0uc53li.netbird.cloud:35566
    tags:
      velocity.forced_host: city-world.mc.minersonline.uk
      enhanced_lobby.display_name: <red>City <blue> World
      enhanced_lobby.icon: minecraft:bricks
      enhanced_lobby.description: <orange>Inactive

  - name: survival
    address: desktop-0uc53li.netbird.cloud:35565
    tags:
      velocity.forced_host: survival.mc.minersonline.uk
      enhanced_lobby.display_name: <green>Survival
      enhanced_lobby.icon: minecraft:iron_pickaxe
      enhanced_lobby.description: Economy, land claiming, and capitalism on top of regular survival world. <orange>Not available 24/7